const LOG_IN = "SIGN_UP";
const LOG_OUT = "LOG_OUT";
const AUTHENTICATED = "AUTHENTICATED";
const MOVIES = "MOVIES";
const ERRORS = "ERRORS";
const LOADINGSTATUS = "LOADINGSTATUS";
const FAV_MOVIES = "FAV_MOVIES";
const REMOVE_FAV_MOVIE = "REMOVE_FAV_MOVIE";

export {
  LOG_IN,
  LOG_OUT,
  AUTHENTICATED,
  MOVIES,
  ERRORS,
  LOADINGSTATUS,
  FAV_MOVIES,
  REMOVE_FAV_MOVIE,
};
